config/routes.rb
QuentManager::Application.routes.draw do
  resources :transacoes

  resources :sobremesas do
    member do
      get :desativar
    end
  end

  resources :pagamentos

  resources :bebidas do
    member do
      get :desativar
    end
  end

  resources :saladas do
    member do
      get :desativar
    end
  end

  resources :guarnicoes do
    member do
      get :desativar
    end
  end

  resources :acompanhamentos do
    member do
      get :desativar
    end
  end    

  resources :empresas do
    member do
      get :bloquear
      get :confirmar_bloqueio
      get :desbloquear
      get :confirmar_desbloqueio
    end
  end

  resources :proteinas do
    member do
      get :desativar
    end
  end

  devise_for :usuarios, :controllers => { :registrations => "registrations"}
  
  #match "/produtos/atualizar/:id" => "produtos#atualizar", via: [:get, :post]
  resources :produtos do
    member do
      get :atualizar
      post :atualizar_estoque
    end
  end

  resources :pedidos do
    member do
      get :confirmar
      get :cancelar
      #get :confirmar_cancelamento
    end
  end    

  resources :clientes do
    member do
      get :conta
      get :lista_pedidos
      get :bloquear
      get :confirmar_bloqueio
      get :desbloquear
      get :confirmar_desbloqueio
    end
  end

    get "home/relatorio_produtos"
    get "home/relatorio_pedidos"
    get "home/pedidos_do_dia"
    get "home/pedidos_empresa"
    get "home/sobre"
    get "home/inicial"
    get "home/vendas"
    get "home/cardapio"
    get "home/conta_clientes"

  resources :home

  root to: "home#index"

  # The priority is based upon pedido of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'produtos/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: produto.id)
  #   get 'produtos/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :produtos

  # Example resource route with options:
  #   resources :produtos do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :produtos do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :produtos do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/produtos/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :produtos
  #   end
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :pedidos
  has_one :conta
  belongs_to :usuario
  belongs_to :empresa
  before_save :corrigir_nome, :criar_conta

  validates :nome, :empresa_id, :celular, :data_de_pagamento, :cpf, :cargo, :setor, :sexo, :data_de_nascimento, :telefone_empresa, presence: true
  validates :cpf, uniqueness: true

  def formatar_data
    data = I18n.l(self.data_de_nascimento)
  end

  def corrigir_nome
    nome = self.nome.titleize
    self.nome = nome
  end

  def nome_abreviado
    nomes = self.nome.split
    if nomes.count > 2
      return nomes[0] + " " + nomes.last
    else
      return self.nome
    end
  end

  def criar_conta
    if self.conta.nil?
      self.conta = Conta.new(:saldo => 0)
    end
  end

  def self.search(search,empresa)
    if search
      search = search.titleize
    end
    if search && !empresa.blank?
      find(:all, :conditions => ['nome LIKE ? AND empresa_id = ?', "%#{search}%", "#{empresa}"])
    elsif search
      find(:all, :conditions => ['nome LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

    def bloqueado?
      self[:bloqueado]
    end

    def desbloqueado?
      !self.bloqueado?
    end

    def bloquear
      self.bloqueado = true
    end

    def bloquear!
      self.bloquear
      self.save!
    end

    def desbloquear
      self.bloqueado = false
    end

    def desbloquear!
      self.desbloquear
      self.save!
    end

  # def data_de_nascimento_str=(data_de_nascimento_str)
  #   self.data_de_nascimento = self.data_de_nascimento_str
  # end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_action :authenticate_usuario!

  # GET /clientes
  # GET /clientes.json
  def index
    if ((current_usuario.admin?) || (current_usuario.gerente?))
      @clientes = Cliente.all.order(:nome => :asc).paginate(:page => params[:page], :per_page => 10).search(params[:search],params[:empresa])
    else
      @clientes = Cliente.find_all_by_id(current_usuario.cliente.id)
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @pedidos = @cliente.pedidos.paginate(:page => params[:page], :per_page => 25).order('created_at DESC')
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
    #Tratando retorno de data do Banco de Dados
    @cliente.data_de_nascimento = @cliente.data_de_nascimento.to_s.split(/\-/).reverse.join('/')
  end

  def conta
    @cliente = Cliente.find(params[:id])
    transacoes = []
    pagamentos = @cliente.conta.pagamentos
    pedidos = @cliente.conta.pedidos.where(:situacao => "Confirmado")
    if !pedidos.empty?
      pedidos.map { |pedido| transacoes << pedido }
    end
    if !pagamentos.empty?
      pagamentos.map { |pagamento| transacoes << pagamento }
    end
    if !transacoes.empty?
      @transacoes = transacoes.sort_by { |t| t.created_at }
    end
    @conta = @cliente.conta
  end

  def bloquear
    @cliente = Cliente.find(params[:id])
  end

  def confirmar_bloqueio
    @cliente = Cliente.find(params[:id])
    @cliente.bloquear!

    if @cliente.save
      BloqueioMailer.bloquear(@cliente.usuario).deliver
      flash[:notice] = "Cliente bloqueado"
    else
      flash[:alert] = "Erro ao bloquear cliente"
    end
    redirect_to clientes_path
  end

  def desbloquear
    @cliente = Cliente.find(params[:id])
  end

  def confirmar_desbloqueio
    @cliente = Cliente.find(params[:id])
    @cliente.desbloquear!

    if @cliente.save
      flash[:notice] = "Cliente bloqueado"
    else
      flash[:alert] = "Erro ao bloquear cliente"
    end
    redirect_to clientes_path
  end


  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)
    @cliente.conta = Conta.new(:saldo => 0)
    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Novo Cliente cadastrado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @cliente }
      else
        format.html { render action: 'new' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end

  def search
    @clientes = Cliente.search params[:search]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :celular, :rg, :telefone_empresa, :numero, :bairro, :cidade, :celular_empresa, :email_empresa, :bloqueado, :telefone, :ramal, :endereco, :complemento, :empresa_id, :sexo, :data_de_nascimento, :data_de_pagamento, :setor, :cargo, :cpf)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_barra_lateral.html.erb
<h1> Estatísticas</h1>
      <p class='info'>Clientes Cadastrados: <%= Cliente.all.count %></p>
      <p class='info'>Clientes Bloqueados: <%= Cliente.where(bloqueado: true).count %></p>
      <p class='info'>Clientes Cadastrados hoje: <%= Cliente.where(created_at: Time.now.beginning_of_day).count %></p>

app/views/clientes/bloquear.html.erb
<%- model_class = Cliente -%>
  <h2>Bloquear Cliente</h2>
  <%#= link_to '#', html_options = {:class => "btn btn-small btn-info informacoes", :id => "_informacoes", :'data-content' => "Administrador Operacional bloqueia o acesso de um Cliente ao sistema.", :rel => "popover"} do %>
      <!-- <i class="icon-info-sign icon-white"></i> -->
  <%# end %>
<div class="show1">
<fieldset class='form-clientes'>
<legend>Dados do cliente a ser bloqueado</legend>

<!--   <div class="span2">
    <%#= render "side_bar" %>
  </div> -->
  <!--end sidebar-->

  <!--div class="span10"-->

    <strong><%= model_class.human_attribute_name(:nome) %>:</strong>
    <%= @cliente.nome %><br>
    <strong><%= model_class.human_attribute_name(:cpf) %>:</strong>
    <%= @cliente.cpf %><br>
    <strong><%= model_class.human_attribute_name(:empresa) %>:</strong>
    <%= @cliente.empresa.nome %><br>
    <strong><%= model_class.human_attribute_name(:celular) %>:</strong>
    <%= @cliente.celular %><br>
</fieldset>
</div>

   <%= link_to t('.cancelar', :default => t("helpers.links.cancelar")),
                clientes_path, :class => 'button gray-voltar' %>
    <%= link_to 'Confirmar Bloqueio', confirmar_bloqueio_cliente_path(@cliente), :class => "button purple" %>

app/views/clientes/conta.html.erb
<%- model_class = Conta -%>
<div class="page-header">
  <h2>
    <center><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %><br/></center>
    <%#= link_to 'Cadastrar Empresa', new_empresa_path, :class=>"button blue-cadastrar-top" %>
    Cliente: <%= Cliente.find_by_id(params[:id].to_i).nome %>
  </h2>
        
</div>
<% if @transacoes.nil? %>
    Este cliente não possui transações na conta.
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><center>Tipo</center> </th>
      <th><center>Valor</center></th>
      <th><center>Data</center></th>
      <th><center>Forma de Pagamento</center></th>
      <% if current_usuario.admin? || current_usuario.gerente? %>
      <th class="text-center"><%=t '.ações', :default => t("helpers.ações") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @transacoes.each do |transacao| %>

      <tr>
        <td><center><%= transacao.class %></center></td>
        <td><center>R$ <%= transacao.valor.to_f %></center></td>
        <% if transacao.class.to_s == "Pagamento" %>
          <td><center><%= transacao.data.strftime("%d/%m/%Y") %></center></td>
          <td><center><%= transacao.forma_de_pagamento %></center></td>
          <% if current_usuario.admin? || current_usuario.gerente? %>
            <td class="text-center">
              <%= link_to edit_pagamento_path(transacao,:conta_id => transacao.conta.id), html_options = { :class => 'btn btn-warning btn-sm', :title => "Editar Dados"} do %>
                          <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
            </td>
          <% end %>
        <% else %>
          <td><center><%= transacao.created_at.strftime("%d/%m/%Y") %></center></td>
          <td><center>Pedido</center></td>        
          <% if current_usuario.admin? || current_usuario.gerente? %>
            <td class="text-center">
              <%= link_to edit_pedido_path(transacao), html_options = { :class => 'btn btn-warning btn-sm', :title => "Editar Dados"} do %>
                          <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
            <%= link_to cancelar_pedido_path(transacao), html_options = {:class => "btn btn-danger btn-sm", :title => "Cancelar Pedido", :id => "cancelar_#{transacao.id}"} do %>
                      <span class="glyphicon glyphicon-remove"></span>
            <% end %>              
            </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <div class="col-md-12 text-center">   
    <div class='saldo_conta'>Saldo Atual: R$ <%= @conta.saldo.to_f %></div>
  </div>
</div>
<% end %>

app/views/clientes/edit.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.editar', 'Editar %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/clientes/index.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h2 class='titulo'><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %><br/></h2>
</div>
<br>
<div class="form-group">
<%= form_tag(clientes_path, :method => "get", :class => "form-horizontal", id: "search-form") do %>
    <div class="col-sm-2">
      <label>
        <%= text_field_tag :search, params[:search], :class => "form-control", placeholder: "Nome do Cliente" %>
      </label>
    </div>
    <div class="col-sm-2">
      <label >
        <%= select_tag :empresa, options_from_collection_for_select(Empresa.all, "id", "nome"), :prompt => "Todas as Empresas", :class => "form-control input-search" %>
      </label>
    </div>
    <div class="col-sm-2">
      <label>
        <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-success' %>    
      </label>
    </div>
    <% end %>
</div>
<br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:celular) %></th>
      <th><%= model_class.human_attribute_name(:empresa) %></th>
      <th><%= model_class.human_attribute_name(:bloqueado) %></th>
      <th class="text-center"><%=t '.ações', :default => t("helpers.ações") %></th>
    </tr>
  </thead>
  <tbody>
      <% @clientes.each do |cliente| %>
      <% if !cliente.bloqueado? %>
        <tr>
          <td><%= cliente.nome_abreviado %></td>
          <td><%= cliente.celular %></td>
          <td><%= cliente.empresa.nome %></td>
          <td><%= cliente.bloqueado? ? "Sim" : "Não" %></td>
          <td class="text-center">
              <%= link_to new_pedido_path(:cliente_id => cliente.id), html_options = {:class => "btn btn-primary btn-sm", :title => "Pedido"} do %>
                        <span class="glyphicon glyphicon-cutlery"></span>
              <% end %>                        
            <%= link_to cliente_path(cliente), html_options = { :class => 'btn btn-info btn-sm', :title => "Ver Dados Completos"} do %>
                        <span class="glyphicon glyphicon-list-alt"></span>          
            <% end %>
            <%= link_to edit_cliente_path(cliente), html_options = { :class => 'btn btn-warning btn-sm', :title => "Editar Dados"} do %>
                        <span class="glyphicon glyphicon-pencil"></span>
                        <% end %>
            <% if cliente.bloqueado? %>
              <%= link_to desbloquear_cliente_path(cliente), html_options = {:class => "btn btn-success btn-sm", :title => "Desbloquear", :id => "desbloquear_#{cliente.id}"} do %>
                        <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            <% else %>
              <%= link_to bloquear_cliente_path(cliente), html_options = {:class => "btn btn-danger btn-sm", :title => "Bloquear", :id => "bloquear_#{cliente.id}"} do %>
                        <span class="glyphicon glyphicon-ban-circle"></span>
              <% end %>
              <% end %>
              <%= link_to new_pagamento_path(:conta_id => cliente.conta.id), html_options = {:class => "btn btn-success btn-sm", :title => "Pagamento"} do %>
                        <span class="glyphicon glyphicon-usd"></span>
              <% end %>                        
              <%#= link_to conta_cliente_path(cliente), html_options = {:class => "btn btn-success btn-sm", :title => "Conta"} do %>
                       <!--  <span class="glyphicon glyphicon-euro"></span> -->
              <%# end %>                        
          </td>
        </tr>
      <% else %>
        <tr class="list-group-font-danger">
          <td><%= cliente.nome_abreviado %></td>
          <td><%= cliente.celular %></td>
          <td><%= cliente.empresa.nome %></td>
          <td><%= cliente.bloqueado? ? "Sim" : "Não" %></td>
          <td class="text-center">
              <%= link_to new_pedido_path(:cliente_id => cliente.id), html_options = {:class => "btn btn-primary btn-sm", :title => "Pedido"} do %>
                        <span class="glyphicon glyphicon-cutlery"></span>
              <% end %>                        
            <%= link_to cliente_path(cliente), html_options = { :class => 'btn btn-info btn-sm', :title => "Ver Dados Completos"} do %>
                        <span class="glyphicon glyphicon-list-alt"></span>          
            <% end %>
            <%= link_to edit_cliente_path(cliente), html_options = { :class => 'btn btn-warning btn-sm', :title => "Editar Dados"} do %>
                        <span class="glyphicon glyphicon-pencil"></span>
                        <% end %>
            <% if cliente.bloqueado? %>
              <%= link_to desbloquear_cliente_path(cliente), html_options = {:class => "btn btn-success btn-sm", :title => "Desbloquear", :id => "desbloquear_#{cliente.id}"} do %>
                        <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            <% else %>
              <%= link_to bloquear_cliente_path(cliente), html_options = {:class => "btn btn-danger btn-sm", :title => "Bloquear", :id => "bloquear_#{cliente.id}"} do %>
                        <span class="glyphicon glyphicon-ban-circle"></span>
              <% end %>
              <% end %>
              <%= link_to new_pagamento_path(:conta_id => cliente.conta.id), html_options = {:class => "btn btn-success btn-sm", :title => "Pagamento"} do %>
                        <span class="glyphicon glyphicon-usd"></span>
              <% end %>                        
              <%#= link_to conta_cliente_path(cliente), html_options = {:class => "btn btn-success btn-sm", :title => "Conta"} do %>
                       <!--  <span class="glyphicon glyphicon-euro"></span> -->
              <%# end %>                        
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<div class="row">
         <div class="col-md-12 text-center">
          <%= link_to "Cancelar", home_inicial_path, :class => 'btn btn-default' %>
        </div>
</div>
<% if current_usuario.admin? %>
  <%= will_paginate @clientes, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/clientes/show.html.erb
<%- model_class = Cliente -%>
<h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
 <!--  <%= link_to t('.novo', :default => t("helpers.links.novo_cliente")),
            new_cliente_path, :class => 'button blue-cadastrar-top' %> -->

<br>
<div class="row">
    <div class="col-md-6">
      <ul class="list-group">
        <li class="list-group-item list-group-item-success"><strong> Dados Pessoais</strong> 
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:nome) %>:&nbsp;</strong> 
          <%= @cliente.nome %>
        </li>
        <li class="list-group-item"><strong>
          E-mail:
          <%= @cliente.usuario.email %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:cpf) %>:&nbsp;</strong> 
          <%= @cliente.cpf %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:rg) %>:&nbsp;</strong> 
          <%= @cliente.rg %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:sexo) %>:&nbsp;</strong> 
          <%= @cliente.sexo %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:data_de_nascimento) %>:&nbsp;</strong> 
          <%= @cliente.data_de_nascimento.strftime("%d/%m/%Y") %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:endereco) %>:&nbsp;</strong> 
          <%= @cliente.endereco %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:numero) %>:&nbsp;</strong>
          <%= @cliente.numero %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:bairro) %>:&nbsp;</strong>
          <%= @cliente.bairro %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:cidade) %>:&nbsp;</strong>
          <%= @cliente.cidade %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:complemento) %>:&nbsp;</strong>
          <%= @cliente.complemento %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:telefone) %>:&nbsp;</strong>
          <%= @cliente.telefone %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:celular) %>:&nbsp;</strong>
          <%= @cliente.celular %>
        </li>           
      </ul>
    </div>

    <div class="col-md-6">
      <ul class="list-group">
        <li class="list-group-item list-group-item-success"><strong> Dados Profissionais</strong> 
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:empresa) %>:&nbsp;</strong> 
          <%= @cliente.empresa.nome %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:cargo) %>:&nbsp;</strong>
          <%= @cliente.cargo %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:setor) %>:&nbsp;</strong>
          <%= @cliente.setor %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:telefone_empresa) %>:&nbsp;</strong>
          <%= @cliente.telefone_empresa %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:ramal) %>:&nbsp;</strong>
          <%= @cliente.ramal %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:celular_empresa) %>:&nbsp;</strong>
          <%= @cliente.celular_empresa %>
        </li>        
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:email_empresa) %>:&nbsp;</strong>
          <%= @cliente.email_empresa %>
        </li>
      </ul>
    </div>
</div>

<h2> Dados dos Pedidos</h2> <br><br> 
<table class="table table-striped">
          <thead>
            <tr>
              <th>Valor</th>
              <th>Data</th>
              <th>Situação</th>      
              <th>Descrição</th>      
            </tr>
          </thead>
          <tbody>
            <% @pedidos.each do |pedido| %>
              <tr>
                <td>R$ <%= pedido.valor %></td>
                <td><%= pedido.created_at.strftime("%d/%m/%Y") %></td>
                <td><%= pedido.situacao %></td>
                <td>  <% pedido.pedidos_acompanhamentos.each do |pedido_acompanhamento| %>
                            <%= pedido_acompanhamento.quantidade %> <%= pedido_acompanhamento.acompanhamento.nome %>, 
                           <% end %>
                          <% pedido.pedidos_proteinas.each do |pedido_proteina| %>
                            <%= pedido_proteina.quantidade %> <%= pedido_proteina.proteina.nome %>, 
                          <% end %>

                          <% pedido.pedidos_guarnicoes.each do |pedido_guarnicao| %>
                            <%= pedido_guarnicao.quantidade %> <%= pedido_guarnicao.guarnicao.nome %>, 
                          <% end %>

                          <% pedido.pedidos_saladas.each do |pedido_salada| %>
                            <%= pedido_salada.quantidade %> <%= pedido_salada.salada.nome %>, 
                          <% end %>
                         
                          <% pedido.pedidos_bebidas.each do |pedido_bebida| %>
                            <%= pedido_bebida.quantidade %> <%= pedido_bebida.bebida.nome %>, 
                          <% end %>
                         
                          <% pedido.pedidos_sobremesas.each do |pedido_sobremesa| %>
                            <%= pedido_sobremesa.quantidade %> <%= pedido_sobremesa.sobremesa.nome %>, 
                          <% end %>
              </td>
              </tr>
            <% end %>
          </tbody>
        </table><br>  
<div class="row">
  <div class="col-md-12 text-center">   
    <%= will_paginate @pedidos, renderer: BootstrapPagination::Rails %>
  </div>
</div>
<br>
  <div class="row">
  <div class="col-md-12 text-center">
    Saldo Atual: R$ <%= @cliente.conta.saldo.to_f %>
   </div>
  </div><br><br> 
<div class="row">
  <div class="col-md-12 text-center">
    <div class="btn-group">
          <%= link_to clientes_path, :class => 'btn btn-default' do %>
              <span class="glyphicon glyphicon-arrow-left"></span>
              <% end %>
    </div>
    <div class="btn-group">
            <%= link_to new_pedido_path(:cliente_id => @cliente.id), html_options = {:class => "btn btn-primary", :title => "Pedido"} do %>
                      <span class="glyphicon glyphicon-cutlery"></span>
            <% end %>      
      </div>                
    <div class="btn-group">
      <%= link_to conta_cliente_path(@cliente), html_options = {:class => "btn btn-success", :title => "Conta"} do %>
        <span class="glyphicon glyphicon-euro"></span>
      <% end %>                        
    </div>        
    <div class="btn-group">
          <%= link_to edit_cliente_path(@cliente), :class => 'btn btn-warning' do %>
              <span class="glyphicon glyphicon-pencil"></span>         
          <% end %>
    </div>
    <div class="btn-group">
          <% if can? :bloquear, Cliente %>          
            <% if @cliente.bloqueado? %>
    
              <%= link_to desbloquear_cliente_path(@cliente), html_options = {:class => "btn btn-success", :title => "Desbloquear", :id => "desbloquear_#{@cliente.id}"} do %>
                        <span class="glyphicon glyphicon-plus"></span>
              <% end %>
            <% else %>
              <%= link_to bloquear_cliente_path(@cliente), html_options = {:class => "btn btn-danger", :title => "Bloquear", :id => "bloquear_#{@cliente.id}"} do %>
                        <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            <% end %>
          <% end %>
      </div>    
    </div>
  </div>
  <br><br>
</div>