config/routes.rb
QuentManager::Application.routes.draw do
  resources :transacoes

  resources :sobremesas do
    member do
      get :desativar
    end
  end

  resources :pagamentos

  resources :bebidas do
    member do
      get :desativar
    end
  end

  resources :saladas do
    member do
      get :desativar
    end
  end

  resources :guarnicoes do
    member do
      get :desativar
    end
  end

  resources :acompanhamentos do
    member do
      get :desativar
    end
  end    

  resources :empresas do
    member do
      get :bloquear
      get :confirmar_bloqueio
      get :desbloquear
      get :confirmar_desbloqueio
    end
  end

  resources :proteinas do
    member do
      get :desativar
    end
  end

  devise_for :usuarios, :controllers => { :registrations => "registrations"}
  
  #match "/produtos/atualizar/:id" => "produtos#atualizar", via: [:get, :post]
  resources :produtos do
    member do
      get :atualizar
      post :atualizar_estoque
    end
  end

  resources :pedidos do
    member do
      get :confirmar
      get :cancelar
      #get :confirmar_cancelamento
    end
  end    

  resources :clientes do
    member do
      get :conta
      get :lista_pedidos
      get :bloquear
      get :confirmar_bloqueio
      get :desbloquear
      get :confirmar_desbloqueio
    end
  end

    get "home/relatorio_produtos"
    get "home/relatorio_pedidos"
    get "home/pedidos_do_dia"
    get "home/pedidos_empresa"
    get "home/sobre"
    get "home/inicial"
    get "home/vendas"
    get "home/cardapio"
    get "home/conta_clientes"

  resources :home

  root to: "home#index"

  # The priority is based upon pedido of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'produtos/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: produto.id)
  #   get 'produtos/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :produtos

  # Example resource route with options:
  #   resources :produtos do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :produtos do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :produtos do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/produtos/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :produtos
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
  before_action :authenticate_usuario!, :except => [:index, :sobre]

  def index
    
  end

  def inicial

  end

  def teste

  end

  def vendas
    if params[:data].blank?
      data = DateTime.now
    else
      data = params[:data].to_datetime
    end

    @valor_vendido = Pedido.vendidos(data)
    @confirmados = Pedido.where(:situacao => "Confirmado",created_at: data.beginning_of_day..data.end_of_day).count
    @cancelados = Pedido.where(:situacao => "Cancelado",created_at: data.beginning_of_day..data.end_of_day).count

    @acompanhamentos = [] 
    @qtds_acompanhamento = []
    PedidoAcompanhamento.where(created_at: data.beginning_of_day..data.end_of_day).map { |p| @acompanhamentos << p.acompanhamento.nome; @qtds_acompanhamento << p.quantidade }
    @quantidade_acompanhamento = Hash.new 0

    @acompanhamentos.each_with_index do |acompanhamento,i|
      @quantidade_acompanhamento[acompanhamento] += @qtds_acompanhamento[i]
    end

    @proteinas = []
    @qtds_proteina = []
    PedidoProteina.where(created_at: data.beginning_of_day..data.end_of_day).map { |p| @proteinas << p.proteina.nome; @qtds_proteina << p.quantidade  }
    @quantidade_proteina = Hash.new 0

    @proteinas.each_with_index do |proteina,i|
      @quantidade_proteina[proteina] += @qtds_proteina[i]
    end

    @guarnicoes = []
    @qtds_guarnicao = []
    PedidoGuarnicao.where(created_at: data.beginning_of_day..data.end_of_day).map { |p| @guarnicoes << p.guarnicao.nome; @qtds_guarnicao << p.quantidade }
    @quantidade_guarnicao = Hash.new 0

    @guarnicoes.each_with_index do |guarnicao,i|
      @quantidade_guarnicao[guarnicao] += @qtds_guarnicao[i]
    end

    @saladas = []
    @qtds_salada = []
    PedidoSalada.where(created_at: data.beginning_of_day..data.end_of_day).map { |p| @saladas << p.salada.nome; @qtds_salada << p.quantidade  }
    @quantidade_salada= Hash.new 0

    @saladas.each_with_index do |salada,i|
      @quantidade_salada[salada] += @qtds_salada[i]
    end

    @bebidas = []
    @qtds_bebida = []
    PedidoBebida.where(created_at: data.beginning_of_day..data.end_of_day).map { |p| @bebidas << p.bebida.nome; @qtds_bebida << p.quantidade }
    @quantidade_bebida = Hash.new 0

    @bebidas.each_with_index do |bebida,i|
      @quantidade_bebida[bebida] += @qtds_bebida[i]
    end

    @sobremesas = []
    @qtds_sobremesa = []
    PedidoSobremesa.where(created_at: data.beginning_of_day..data.end_of_day).map { |p| @sobremesas << p.sobremesa.nome; @qtds_sobremesa << p.quantidade }
    @quantidade_sobremesa = Hash.new 0

    @sobremesas.each_with_index do |sobremesa,i|
      @quantidade_sobremesa[sobremesa] += @qtds_sobremesa[i]
    end

  end

  def cardapio

  end

  def conta_clientes
    @clientes = Cliente.select('*').joins(:conta).where('saldo < 0').order(:nome => :asc).search(params[:search],params[:empresa])
   #@clientes = Cliente.all.order(:nome => :asc).paginate(:page => params[:page], :per_page => 10).search(params[:search],params[:empresa])
  end

  def relatorio_produtos
    @produtos_acabando = Produto.acabando_completo
    @produtos_em_falta = Produto.zerados
  end

  def pedidos_do_dia
    @pedidos = Pedido.confirmados_do_dia
  end

  def relatorio_pedidos
    @pedidos_confirmados_do_mes = Pedido.confirmados_do_mes
    @pedidos_cancelados_do_mes = Pedido.cancelados_do_mes
    @pedidos_confirmados_do_dia = Pedido.confirmados_do_dia
    @pedidos_cancelados_do_dia = Pedido.cancelados_do_dia
  end

  def pedidos_empresa
    @pedidos = Pedido.confirmados_do_dia.search("",params[:empresa],"")
      if !params[:empresa].blank?
        @nome_da_empresa = Empresa.find(params[:empresa]).nome
      else
        @nome_da_empresa = "Todas as Empresas"
      end    
    #@pedidos = Pedido.confirmados_do_dia    
  end

  def search
    @pedidos = Pedidos.search params[:empresa]
  end

end

app/views/home/cardapio.html.erb
<center><h1>Cardápio de Hoje</h1></center><br>
  <div class="row">
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/proteina.jpg" class="img-responsive">
            <div class="caption">
              <h3>Proteínas</h3>
              <p><% Proteina.all.where(:disponibilidade => true).each do |proteina| %>
                  <% if Proteina.all.where(:disponibilidade => true).last == proteina %>
                    <%= proteina.nome %>.
                  <% else %>
                    <%= proteina.nome %> ,
                  <% end %>
              <% end %></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/carboidrato.jpg" class="img-responsive">
            <div class="caption">
              <h3>Guarnições</h3>
              <p><% Guarnicao.all.where(:disponibilidade => true).each do |guarnicao| %>
                  <% if Guarnicao.all.where(:disponibilidade => true).last == guarnicao %>
                    <%= guarnicao.nome %>.
                  <% else %>
                    <%= guarnicao.nome %> ,
                  <% end %>
              <% end %></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/acompanhamento.jpg" class="img-responsive">
            <div class="caption">
              <h3>Acompanhamentos</h3>
              <p><% Acompanhamento.all.where(:disponibilidade => true).each do |acompanhamento| %>
                  <% if Acompanhamento.all.where(:disponibilidade => true).last == acompanhamento %>
                    <%= acompanhamento.nome %>.
                  <% else %>
                    <%= acompanhamento.nome %> ,
                  <% end %>
              <% end %>  </p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/salada.jpg" class="img-responsive">
            <div class="caption">
              <h3>Saladas</h3>
              <p>   <% Salada.all.where(:disponibilidade => true).each do |salada| %>
                  <% if Salada.all.where(:disponibilidade => true).last == salada %>
                    <%= salada.nome %>.
                  <% else %>
                    <%= salada.nome %> ,
                  <% end %>
              <% end %> </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/sobremesa.jpg" class="img-responsive">
            <div class="caption">
              <h3>Sobremesas</h3>
              <p><% Sobremesa.all.where(:disponibilidade => true).each do |sobremesa| %>
                  <% if Sobremesa.all.where(:disponibilidade => true).last == sobremesa %>
                    <%= sobremesa.nome %>.
                  <% else %>
                    <%= sobremesa.nome %> ,
                  <% end %>
              <% end %>  </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/bebidas.jpg" class="img-responsive">
            <div class="caption">
              <h3>Bebidas</h3>
              <p><% Bebida.all.where(:disponibilidade => true).each do |bebida| %>
                  <% if Bebida.all.where(:disponibilidade => true).last == bebida %>
                    <%= bebida.nome %>.
                  <% else %>
                    <%= bebida.nome %> ,
                  <% end %>
              <% end %></p>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/home/conta_clientes.html.erb
<%- model_class = Cliente -%>
<div class="page-header noprint">
  <center><h2>Conta dos Clientes<span class="estoque"></span></h2></center>
</div>
<br>
<div class="form-group noprint">
<%= form_tag(home_conta_clientes_path, :method => "get", :class => "form-horizontal", id: "search-form") do %>
    <div class="col-sm-2">
      <label>
        <%= text_field_tag :search, params[:search], :class => "form-control", placeholder: "Nome do Cliente" %>
      </label>
    </div>
    <div class="col-sm-2">
      <label >
        <%= select_tag :empresa, options_from_collection_for_select(Empresa.all, "id", "nome"), :prompt => "Todas as Empresas", :class => "form-control input-search" %>
      </label>
    </div>
    <div class="col-sm-1">
      <label>
        <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-success' %>
      </label>
    </div>
    <div class="col-sm-2">
      <label>
        <input class='btn btn-default' type="button" onClick="window.print()" value="Imprimir"/>
      </label>
    </div>    
    <% end %>
</div>
<br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:celular) %></th>
      <th><%= model_class.human_attribute_name(:empresa) %></th>
      <th><%= model_class.human_attribute_name(:setor) %></th>
      <th><%= model_class.human_attribute_name(:saldo) %></th>
      <th class="text-center noprint"><%=t '.ações', :default => t("helpers.ações") %></th>
    </tr>
  </thead>
  <tbody>
      <% @clientes.each_with_index do |cliente,i| %>
      <% if !cliente.bloqueado? %>
        <tr>
          <td><%= cliente.nome_abreviado %></td>
          <td><%= cliente.celular %></td>
          <td><%= cliente.empresa.nome %></td>
          <td><%= cliente.setor %></td>
          <td>R$ <%= cliente.conta.saldo.to_f %></td>
          <td class="text-center noprint">
            <%= link_to cliente_path(cliente), html_options = { :class => 'btn btn-info btn-sm', :title => "Ver Dados Completos"} do %>
                        <span class="glyphicon glyphicon-list-alt"></span>          
            <% end %>
              <%= link_to conta_cliente_path(cliente), html_options = {:class => "btn btn-success btn-sm", :title => "Conta"} do %>
                       <span class="glyphicon glyphicon-euro"></span>
              <% end %>                        
            <% if cliente.bloqueado? %>
              <%= link_to desbloquear_cliente_path(cliente), html_options = {:class => "btn btn-success btn-sm", :title => "Desbloquear", :id => "desbloquear_#{cliente.id}"} do %>
                        <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            <% else %>
              <%= link_to bloquear_cliente_path(cliente), html_options = {:class => "btn btn-danger btn-sm", :title => "Bloquear", :id => "bloquear_#{cliente.id}"} do %>
                        <span class="glyphicon glyphicon-ban-circle"></span>
              <% end %>
              <% end %>
              <%= link_to new_pagamento_path(:conta_id => cliente.conta.id), html_options = {:class => "btn btn-success btn-sm", :title => "Pagamento"} do %>
                        <span class="glyphicon glyphicon-usd"></span>
              <% end %>                        
          </td>
        </tr>
      <% else %>
        <tr class="list-group-font-danger">
          <td><%= cliente.nome_abreviado %></td>
          <td><%= cliente.celular %></td>
          <td><%= cliente.empresa.nome %></td>
          <td><%= cliente.setor %></td>          
          <td><%= cliente.bloqueado? ? "Sim" : "Não" %></td>
          <td class="text-center">
            <%= link_to cliente_path(cliente), html_options = { :class => 'btn btn-info btn-sm', :title => "Ver Dados Completos"} do %>
                        <span class="glyphicon glyphicon-list-alt"></span>          
            <% end %>
              <%= link_to conta_cliente_path(cliente), html_options = {:class => "btn btn-success btn-sm", :title => "Conta"} do %>
                       <span class="glyphicon glyphicon-euro"></span>
              <% end %>                        
            <% if cliente.bloqueado? %>
              <%= link_to desbloquear_cliente_path(cliente), html_options = {:class => "btn btn-success btn-sm", :title => "Desbloquear", :id => "desbloquear_#{cliente.id}"} do %>
                        <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            <% else %>
              <%= link_to bloquear_cliente_path(cliente), html_options = {:class => "btn btn-danger btn-sm", :title => "Bloquear", :id => "bloquear_#{cliente.id}"} do %>
                        <span class="glyphicon glyphicon-ban-circle"></span>
              <% end %>
              <% end %>
              <%= link_to new_pagamento_path(:conta_id => cliente.conta.id), html_options = {:class => "btn btn-success btn-sm", :title => "Pagamento"} do %>
                        <span class="glyphicon glyphicon-usd"></span>
              <% end %>                        
          </td>
        </tr>
      <% end %>
      <% if ((i+1) % 27) == 0 %>
        <div class="break"> </div>
      <% end %>      
    <% end %>
  </tbody>
</table>
<br>

<div class="row noprint">
         <div class="col-md-12 text-center">
          <%= link_to "Cancelar", home_inicial_path, :class => 'btn btn-default' %>
        </div>
</div>

app/views/home/inicial.html.erb
<% if current_usuario.gerente? %>

<br><br>
<div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Informações dos Clientes</h3>
            </div>
            <div class="panel-body">
              <p>Clientes Cadastrados: <%= Cliente.all.count %></p>
              <p>Clientes Bloqueados: <%= Cliente.where(bloqueado: true).count %></p>
              <p>Clientes Cadastrados hoje: <%= Cliente.where(created_at: Time.now.beginning_of_day).count %></p>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Informações de Vendas</h3>
            </div>
            <div class="panel-body">
              <p>Pedidos Confirmados: <%= Pedido.confirmados_do_mes.count %></p> 
              <p>Pedidos Cancelados: <%= Pedido.cancelados_do_mes.count %></p> 
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Informações dos Pedidos de Hoje</h3>
            </div>
            <div class="panel-body">
              <p>Pedidos Confirmados: <%= Pedido.confirmados_do_dia.count %></p>
              <p>Pedidos Cancelados: <%= Pedido.cancelados_do_dia.count %></p>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Informações do Estoque</h3>
            </div>
            <div class="panel-body">
              <p><strong>Acabando:</strong> <%= Produto.acabando.count %></p>
              <p><strong>Em falta:</strong> <%= Produto.zerados.count %></p>            
              <center><%= link_to 'Detalhes', home_relatorio_produtos_path %> </center>
            </div>
          </div>
        </div>
  </div>

<% elsif current_usuario.admin? %>

<br><br>
<div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Informações dos Clientes</h3>
            </div>
            <div class="panel-body">
              <p>Clientes Cadastrados: <%= Cliente.all.count %></p>
              <p>Clientes Bloqueados: <%= Cliente.where(bloqueado: true).count %></p>
              <p>Clientes Cadastrados hoje: <%= Cliente.where(created_at: Time.now.beginning_of_day).count %></p>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Informações de Vendas</h3>
            </div>
            <div class="panel-body">
              <p>Valor vendido hoje: R$ <%= exibir_decimal(Pedido.vendidos_hoje) %></p>
              <p>Vendas do mês: R$<%= exibir_decimal(Pedido.vendas_do_mes) %></p> 
              <p>Pedidos Confirmados: <%= Pedido.confirmados_do_mes.count %></p> 
              <p>Pedidos Cancelados: <%= Pedido.cancelados_do_mes.count %></p> 
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Informações dos Pedidos de Hoje</h3>
            </div>
            <div class="panel-body">
              <p>Valor vendido hoje: R$<%= exibir_decimal(Pedido.vendidos_hoje) %></p>
              <p>Pedidos Confirmados: <%= Pedido.confirmados_do_dia.count %></p>
              <p>Pedidos Cancelados: <%= Pedido.cancelados_do_dia.count %></p>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Informações do Estoque</h3>
            </div>
            <div class="panel-body">
              <p><strong>Acabando:</strong> <%= Produto.acabando.count %></p>
              <p><strong>Em falta:</strong> <%= Produto.zerados.count %></p>            
              <center><%= link_to 'Detalhes', home_relatorio_produtos_path %> </center>
            </div>
          </div>
        </div>
  </div>
  <% else %>
<br>
<center><h1>Cardápio de Hoje</h1></center><br>
  <div class="row">
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/proteina.jpg" class="img-responsive">
            <div class="caption">
              <h3>Proteínas</h3>
              <p><% Proteina.all.where(:disponibilidade => true).each do |proteina| %>
                  <% if Proteina.all.where(:disponibilidade => true).last == proteina %>
                    <%= proteina.nome %>.
                  <% else %>
                    <%= proteina.nome %> ,
                  <% end %>
              <% end %></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/carboidrato.jpg" class="img-responsive">
            <div class="caption">
              <h3>Guarnições</h3>
              <p><% Guarnicao.all.where(:disponibilidade => true).each do |guarnicao| %>
                  <% if Guarnicao.all.where(:disponibilidade => true).last == guarnicao %>
                    <%= guarnicao.nome %>.
                  <% else %>
                    <%= guarnicao.nome %> ,
                  <% end %>
              <% end %></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/acompanhamento.jpg" class="img-responsive">
            <div class="caption">
              <h3>Acompanhamentos</h3>
              <p><% Acompanhamento.all.where(:disponibilidade => true).each do |acompanhamento| %>
                  <% if Acompanhamento.all.where(:disponibilidade => true).last == acompanhamento %>
                    <%= acompanhamento.nome %>.
                  <% else %>
                    <%= acompanhamento.nome %> ,
                  <% end %>
              <% end %>  </p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/salada.jpg" class="img-responsive">
            <div class="caption">
              <h3>Saladas</h3>
              <p>   <% Salada.all.where(:disponibilidade => true).each do |salada| %>
                  <% if Salada.all.where(:disponibilidade => true).last == salada %>
                    <%= salada.nome %>.
                  <% else %>
                    <%= salada.nome %> ,
                  <% end %>
              <% end %> </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/sobremesa.jpg" class="img-responsive">
            <div class="caption">
              <h3>Sobremesas</h3>
              <p><% Sobremesa.all.where(:disponibilidade => true).each do |sobremesa| %>
                  <% if Sobremesa.all.where(:disponibilidade => true).last == sobremesa %>
                    <%= sobremesa.nome %>.
                  <% else %>
                    <%= sobremesa.nome %> ,
                  <% end %>
              <% end %>  </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="../images/bebidas.jpg" class="img-responsive">
            <div class="caption">
              <h3>Bebidas</h3>
              <p><% Bebida.all.where(:disponibilidade => true).each do |bebida| %>
                  <% if Bebida.all.where(:disponibilidade => true).last == bebida %>
                    <%= bebida.nome %>.
                  <% else %>
                    <%= bebida.nome %> ,
                  <% end %>
              <% end %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  
    <div class="container white"><br><hr>
      <center><b><h3>Conta</h3></b><p>Quantidade de pedidos:  <%= current_usuario.cliente.pedidos.count %></p>
      <p>Saldo atual: R$<%= current_usuario.cliente.conta.saldo.to_f %></p></center>
  <br><br>
</div>
<% end %>

app/views/home/sobre.html.erb
História da empresa aqui

app/views/home/vendas.html.erb
<center><h2>Relatório de Pedidos<span class="estoque"></span></h2></center>
<br>
<div class="form-group noprint">
  <%= form_tag(home_vendas_path, :method => "get", :class => "validate", id: "search-formulario") do %>
    <div class="col-sm-2">
      <label>
      <%= text_field_tag :data, params[:data], :class => "form-control", placeholder: "Data" %><br>
      </label>
    </div>      

      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
    <div class="col-sm-2">
      <label>           
        <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-success' %>
      </label>
    </div>
</div>
    <br>
  <% end %>
<br><br>
<div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Vendas</h3>
            </div>
            <div class="panel-body">
                <% if current_usuario.admin? %>
                  <p>Valor vendido: R$ <%= exibir_decimal(@valor_vendido) %></p> 
                <% end %>
              <p>Pedidos Confirmados: <%= @confirmados %></p> 
              <p>Pedidos Cancelados: <%= @cancelados %></p> 
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Acompanhamentos</h3>
            </div>
            <div class="panel-body">
              <% if !@quantidade_acompanhamento.blank? %>
                <% @quantidade_acompanhamento.each do |k,v| %>
                  <p><%= k %>: <%= v %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
</div>
<div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Proteínas</h3>
            </div>
            <div class="panel-body">
              <% if !@quantidade_proteina.blank? %>
                <% @quantidade_proteina.each do |k,v| %>
                  <p><%= k %>: <%= v %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Guarnições</h3>
            </div>
            <div class="panel-body">
              <% if !@quantidade_guarnicao.blank? %>
                <% @quantidade_guarnicao.each do |k,v| %>
                  <p><%= k %>: <%= v %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
</div>
<div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Saladas</h3>
            </div>
            <div class="panel-body">
              <% if !@quantidade_salada.blank? %>
                <% @quantidade_salada.each do |k,v| %>
                  <p><%= k %>: <%= v %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Bebidas</h3>
            </div>
            <div class="panel-body">
              <% if !@quantidade_bebida.blank? %>
                <% @quantidade_bebida.each do |k,v| %>
                  <p><%= k %>: <%= v %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

  </div>