config/routes.rb
QuentManager::Application.routes.draw do
  resources :transacoes

  resources :sobremesas do
    member do
      get :desativar
    end
  end

  resources :pagamentos

  resources :bebidas do
    member do
      get :desativar
    end
  end

  resources :saladas do
    member do
      get :desativar
    end
  end

  resources :guarnicoes do
    member do
      get :desativar
    end
  end

  resources :acompanhamentos do
    member do
      get :desativar
    end
  end    

  resources :empresas do
    member do
      get :bloquear
      get :confirmar_bloqueio
      get :desbloquear
      get :confirmar_desbloqueio
    end
  end

  resources :proteinas do
    member do
      get :desativar
    end
  end

  devise_for :usuarios, :controllers => { :registrations => "registrations"}
  
  #match "/produtos/atualizar/:id" => "produtos#atualizar", via: [:get, :post]
  resources :produtos do
    member do
      get :atualizar
      post :atualizar_estoque
    end
  end

  resources :pedidos do
    member do
      get :confirmar
      get :cancelar
      #get :confirmar_cancelamento
    end
  end    

  resources :clientes do
    member do
      get :conta
      get :lista_pedidos
      get :bloquear
      get :confirmar_bloqueio
      get :desbloquear
      get :confirmar_desbloqueio
    end
  end

    get "home/relatorio_produtos"
    get "home/relatorio_pedidos"
    get "home/pedidos_do_dia"
    get "home/pedidos_empresa"
    get "home/sobre"
    get "home/inicial"
    get "home/vendas"
    get "home/cardapio"
    get "home/conta_clientes"

  resources :home

  root to: "home#index"

  # The priority is based upon pedido of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'produtos/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: produto.id)
  #   get 'produtos/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :produtos

  # Example resource route with options:
  #   resources :produtos do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :produtos do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :produtos do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/produtos/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :produtos
  #   end
end

app/controllers/transacoes_controller.rb
class TransacoesController < ApplicationController
  before_action :set_transacao, only: [:show, :edit, :update, :destroy]

  # GET /transacoes
  # GET /transacoes.json
  def index
    @transacoes = Transacao.all
  end

  # GET /transacoes/1
  # GET /transacoes/1.json
  def show
  end

  # GET /transacoes/new
  def new
    @transacao = Transacao.new
  end

  # GET /transacoes/1/edit
  def edit
  end

  # POST /transacoes
  # POST /transacoes.json
  def create

    quantidade = params[:transacao][:quantidade]
    params[:transacao][:quantidade] = quantidade.split( ',').join('.')  

    @transacao = Transacao.new(transacao_params)

    respond_to do |format|
      if @transacao.save
        format.html { redirect_to @transacao.produto, notice: 'Operação realizada com sucesso!' }
        format.json { render action: 'show', status: :created, location: @transacao }
      else
        format.html { render action: 'new' }
        format.json { render json: @transacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transacoes/1
  # PATCH/PUT /transacoes/1.json
  def update
    quantidade = params[:transacao][:quantidade]
    params[:transacao][:quantidade] = quantidade.split( ',').join('.')  
    
    respond_to do |format|
      if @transacao.update(transacao_params)
        format.html { redirect_to @transacao.produto, notice: 'Operação atualizada com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transacoes/1
  # DELETE /transacoes/1.json
  def destroy
    @transacao.destroy
    respond_to do |format|
      format.html { redirect_to transacoes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transacao
      @transacao = Transacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transacao_params
      params.require(:transacao).permit(:produto_id, :valor, :quantidade, :tipo)
    end
end

app/helpers/transacoes_helper.rb
module TransacoesHelper
end

app/views/transacoes/_form.html.erb
<%= form_for @transacao, :html => { :class => 'form-horizontal validate' } do |f| %>
  <% if @transacao.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @transacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <%= f.hidden_field :produto_id, :value => params[:produto_id].to_i %>
<div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Operação em <%= Produto.find(params[:produto_id].to_i).nome %> </h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <div class="col-sm-2">
                    <label class="control-label">Quantidade</label>
                  </div>
                  <div class="col-sm-10">
                    <%= f.text_field :quantidade, :class => 'form-control required numeric' %>                    
                    <span class="validate">Quantidade</span>
                  </div>
                </div>                
                <div class="form-group">
                  <div class="col-sm-2">
                    <label class="control-label">Tipo</label>
                  </div>
                  <div class="col-sm-5">
                    <%= f.select :tipo, options_for_select([["Entrada",1] , ["Saída",2]]), {:prompt => "Tipo de Operação"}, {:class => 'form-control input-search required'} %>
                    <span class="validate">Selecione um item</span>
                  </div>
                </div>                
                                
            </div>
          </div>
        </div>
  </div><br>
 <div class="row">
        <div class="col-md-6 text-right">          
          <%= f.submit "Finalizar Operação", :class => 'btn btn-primary' %>
        </div>
        <div class="col-md-6">
          <%= link_to "Cancelar", produtos_path, :class => 'btn btn-default' %>
        </div>
</div>

<% end %>

app/views/transacoes/edit.html.erb
<h2>Editing transacao</h2>

<%= render 'form' %>

<%= link_to 'Show', @transacao %> |
<%= link_to 'Back', transacoes_path %>

app/views/transacoes/index.html.erb
<h2>Bebidas</h2> <br>
<%- model_class = Bebida -%>
<div class="row">
        <div class="col-md-6 "> 
        <%= link_to "Nova Bebida", new_bebida_path, :class => 'btn btn-primary' %>                  
        </div>        
</div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:qtd) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:disponibilidade) %></th>
      <th width="164px"><center><%=t '.ações', :default => t("helpers.ações") %></center></th>
    </tr>
  </thead>
  <tbody>
    <% @bebidas.each do |bebida| %>
      <% if bebida.disponibilidade? %>
        <tr>
          <td><%= bebida.nome %></td>
          <td><%= bebida.quantidade %></td>
          <td>R$<%= exibir_decimal(bebida.valor) %></td>
          <td><% if bebida.disponibilidade? %> Ativado <% else %> Desativado <% end %></td>
          <td>
            <%= link_to edit_bebida_path(bebida), html_options = { :class => 'btn btn-warning btn-sm', :title => "Editar Dados"} do %>
                    <span class="glyphicon glyphicon-pencil"></span>
                        <% end %>
            <%= link_to bebida_path(bebida), html_options = { :class => 'btn btn-info btn-sm', :title => "Ver Dados Completos"} do %>
                    <span class="glyphicon glyphicon-list-alt"></span>
            <% end %>
            <% if bebida.disponibilidade? %>
              <%= link_to desativar_bebida_path(bebida), html_options = { :class => 'btn btn-danger btn-sm', :title => "Desativar"} do %>
                      <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            <% else %>
              <%= link_to edit_bebida_path(bebida), html_options = { :class => 'btn btn-success btn-sm', :title => "Ativar"} do %>
                <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% else %>
        <tr class="list-group-font-danger">
          <td><%= bebida.nome %></td>
          <td><%= bebida.quantidade %></td>
          <td>R$<%= exibir_decimal(bebida.valor) %></td>
          <td><% if bebida.disponibilidade? %> Ativado <% else %> Desativado <% end %></td>
          <td>
            <%= link_to edit_bebida_path(bebida), html_options = { :class => 'btn btn-warning btn-sm', :title => "Editar Dados"} do %>
                    <span class="glyphicon glyphicon-pencil"></span>
                        <% end %>
            <%= link_to bebida_path(bebida), html_options = { :class => 'btn btn-info btn-sm', :title => "Ver Dados Completos"} do %>
                    <span class="glyphicon glyphicon-list-alt"></span>
            <% end %>
            <% if bebida.disponibilidade? %>
              <%= link_to desativar_bebida_path(bebida), html_options = { :class => 'btn btn-danger btn-sm', :title => "Desativar"} do %>
                      <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            <% else %>
              <%= link_to edit_bebida_path(bebida), html_options = { :class => 'btn btn-success btn-sm', :title => "Ativar"} do %>
                <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%= will_paginate @transacoes, renderer: BootstrapPagination::Rails %>

<div class="row">
        <div class="col-md-6 text-right "> 
        <%= link_to "Nova Bebida", new_transacao_path, :class => 'btn btn-primary' %>                  
        </div>        
         <div class="col-md-6">
          <%= link_to "Cancelar", home_inicial_path, :class => 'btn btn-default' %>
        </div>
</div>


<h2>Listing transacoes</h2>

<table>
  <thead>
    <tr>
      <th>Produto</th>
      <th>Valor</th>
      <th>Quantidade</th>
      <th>Tipo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transacoes.each do |transacao| %>
      <tr>
        <td><%= transacao.produto_id %></td>
        <td><%= transacao.valor %></td>
        <td><%= transacao.quantidade %></td>
        <td><%= transacao.tipo %></td>
        <td><%= link_to 'Show', transacao %></td>
        <td><%= link_to 'Edit', edit_transacao_path(transacao) %></td>
        <td><%= link_to 'Destroy', transacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transacao', new_transacao_path %>

app/views/transacoes/new.html.erb
<h2>Nova Operação</h2>

<%= render 'form' %>

app/views/transacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Produto:</strong>
  <%= @transacao.produto_id %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @transacao.valor %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @transacao.quantidade %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @transacao.tipo %>
</p>

<%= link_to 'Edit', edit_transacao_path(@transacao) %> |
<%= link_to 'Back', transacoes_path %>