config/routes.rb
QuentManager::Application.routes.draw do
  resources :transacoes

  resources :sobremesas do
    member do
      get :desativar
    end
  end

  resources :pagamentos

  resources :bebidas do
    member do
      get :desativar
    end
  end

  resources :saladas do
    member do
      get :desativar
    end
  end

  resources :guarnicoes do
    member do
      get :desativar
    end
  end

  resources :acompanhamentos do
    member do
      get :desativar
    end
  end    

  resources :empresas do
    member do
      get :bloquear
      get :confirmar_bloqueio
      get :desbloquear
      get :confirmar_desbloqueio
    end
  end

  resources :proteinas do
    member do
      get :desativar
    end
  end

  devise_for :usuarios, :controllers => { :registrations => "registrations"}
  
  #match "/produtos/atualizar/:id" => "produtos#atualizar", via: [:get, :post]
  resources :produtos do
    member do
      get :atualizar
      post :atualizar_estoque
    end
  end

  resources :pedidos do
    member do
      get :confirmar
      get :cancelar
      #get :confirmar_cancelamento
    end
  end    

  resources :clientes do
    member do
      get :conta
      get :lista_pedidos
      get :bloquear
      get :confirmar_bloqueio
      get :desbloquear
      get :confirmar_desbloqueio
    end
  end

    get "home/relatorio_produtos"
    get "home/relatorio_pedidos"
    get "home/pedidos_do_dia"
    get "home/pedidos_empresa"
    get "home/sobre"
    get "home/inicial"
    get "home/vendas"
    get "home/cardapio"
    get "home/conta_clientes"

  resources :home

  root to: "home#index"

  # The priority is based upon pedido of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'produtos/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: produto.id)
  #   get 'produtos/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :produtos

  # Example resource route with options:
  #   resources :produtos do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :produtos do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :produtos do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/produtos/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :produtos
  #   end
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  has_many :item_de_pedidos
  has_many :pedidos, through: :item_de_pedidos
  has_many :transacoes
  belongs_to :produto_tipo
  belongs_to :produto_categoria

  validates :produto_categoria_id, :nome, :quantidade, :limite_minimo, presence: true
  validates :nome, uniqueness: true  

  scope :bebidas, -> { where(categoria: "Bebida") }
  scope :selecionaveis, -> { where(categoria: "Bebida" || "Sobremesa") }


  def atualizar(quantidade)
    self.quantidade = self.quantidade + quantidade
    self.save
  end

  def abaixo_do_limite?
    if  self.quantidade <= self.limite_minimo
      return true
    else
      return false
    end
  end

  def exibicao_select
    "#{self.nome} #{self.tipo}"
  end

  def self.em_falta
    total=0
    Produto.all.each do |p|
      if p.quantidade == 0
        total = total +1
      end
    end
      return total    
  end

  def self.em_alerta
    total=0
    Produto.all.each do |p|
      if p.abaixo_do_limite?
        total = total +1
      end
    end
      return total
  end
  
  def self.acabando
    produtos = []
    Produto.all.map { |p| produtos << p if p.abaixo_do_limite? && !(p.quantidade == 0)  }
    limite_exibicao = []
    for i in 0..2 do
      if !produtos[i].blank?
        limite_exibicao << produtos[i]
      end
    end
    return limite_exibicao
  end

  def self.search(search)
    if search
      search = search.titleize
    end
    if search
      find(:all, :conditions => ['nome LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end  


  def self.acabando_completo
    produtos = []
    Produto.all.map { |p| produtos << p if p.abaixo_do_limite? && !(p.quantidade == 0) }
    return produtos
  end

  def self.zerados
    produtos = []
    Produto.all.map { |p| produtos << p if p.quantidade == 0 }
    return produtos
  end

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_action :authenticate_usuario!

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all.order(:nome => :asc).paginate(:page => params[:page], :per_page => 10).search(params[:search])
    #Produto.paginate(:page => params[:page], :per_page => 30)
    #@produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    quantidade = params[:produto][:quantidade]
    params[:produto][:quantidade] = quantidade.split( ',').join('.')  

    @produto = Produto.new(produto_params)
    @produto.nome = @produto.nome.titleize

    respond_to do |format|
      if @produto.save
        format.html { flash[:notice] = 'Produto cadastrado com sucesso.'
                                redirect_to @produto }
        format.json { render action: 'show', status: :created, location: @produto }
      else
        format.html { render action: 'new' }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    quantidade = params[:produto][:quantidade]
    params[:produto][:quantidade] = quantidade.split( ',').join('.')  

    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end

  def atualizar

  end

  def atualizar_estoque
    produto = Produto.find(params[:id])
    quantidade = params[:qtd].to_i
    if params[:tipo] == "Adicionar"
      produto.atualizar(quantidade)
    elsif params[:tipo] == "Subtrair"
      quantidade = quantidade * (-1)
      produto.atualizar(quantidade)
    end
    redirect_to produto_path(produto)
  end

  def search
    @produtos = Produtos.search params[:search]
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :produto_categoria_id, :produto_tipo_id, :quantidade, :limite_minimo, :categoria)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
  def unidade_medida(produto)
    #debugger
    if ["Lata","Copo","Pet 600ml", "Pet 2l", "Unidade", "Embalagem Individual", "Garrafa 500ml", "Garrafa 1l", "Caixa", "Pacote", "Sache"].include? produto.produto_tipo.nome
      return "un"
    elsif produto.produto_tipo.nome == "Kilo"
      return "kg"
    elsif produto.produto_tipo.nome == "Grama"
      return "g"
    elsif produto.produto_tipo.nome == "Litro"
      return "l"
    end
  end
end

app/views/produtos/_barra_lateral.html.erb
<h1> Estatísticas</h1>
      <p class='info'>Produtos em Alerta: <%= Produto.em_alerta %></p>
      <p class='info'>Produtos em Falta: <%= Produto.em_falta %></p>

app/views/produtos/_form.html.erb
<%= form_for @produto, :html => { :class => 'form-horizontal validate' } do |f| %>

  <% @produto.errors.full_messages.each do |msg| %>
    <li><%= msg %></li><br/>
  <% end %>

<div class="row">
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Produto</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <div class="col-sm-2">
                    <label class="control-label">Nome</label>
                  </div>
                  <div class="col-sm-10">
                    <%= f.text_field :nome, :class => 'form-control required' %>                    
                    <span class="validate">Nome</span>
                  </div>
                </div>                
                <div class="form-group">
                  <div class="col-sm-2">
                    <label class="control-label">Categoria</label>
                  </div>
                  <div class="col-sm-5">
                    <%= f.collection_select :produto_categoria_id, ProdutoCategoria.all, :id, :nome, {:prompt => "Selecione"} , { :class => 'form-control required' } %>
                    <span class="validate">Selecione um item</span>
                  </div>
                </div>                
                <div class="form-group">
                  <div class="col-sm-2">
                    <label class="control-label">Tipo</label>
                  </div>
                  <div class="col-sm-5">
                    <%= f.collection_select :produto_tipo_id, ProdutoTipo.all, :id, :nome, {:prompt => "Selecione"} , { :class => 'form-control required' } %>
                    <span class="validate">Selecione um item</span>
                  </div>
                </div>                 
                <div class="form-group">
                  <div class="col-sm-3">
                    <label class="control-label">Quantidade</label>
                  </div>
                  <div class="col-sm-9">
                    <%= f.text_field :quantidade, :class => 'form-control required numeric' %>
                    <span class="validate">Quantidade</span>
                  </div>
                </div> 
                <div class="form-group">
                    <div class="col-sm-3">
                      <label class="control-label">Limite Mínimo</label>
                    </div>
                    <div class="col-sm-9">
                      <%= f.text_field :limite_minimo, :class => 'form-control required numeric' %>
                      <span class="validate">Limite Mínimo</span>
                    </div>
                  </div>                 
                </div>
          </div>
        </div>
  </div>
  <br>
  <div class="row">
        <div class="col-md-6 text-right">          
          <%= f.submit nil, :class => 'btn btn-primary' %>
        </div>
        <div class="col-md-6">
          <%= link_to "Cancelar", produtos_path, :class => 'btn btn-default' %>
        </div>
</div>
<% end %>

app/views/produtos/atualizar.html.erb
<%- model_class = Produto -%>
<h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editar %{model}'], :model => model_class.model_name.human.titleize %>
<br><%= Produto.find_by_id(params[:id].to_i).nome %> </h1>

<%= form_for "produto", :url => atualizar_estoque_produto_path, :html => { :class => 'validate' } do  %>
 <table>
  <td><p>
    <%#= f.label :nome, :class => 'control-label' %>
    
      <%#= f.text_field :nome, :class => 'text_field' %>

    <%= label_tag :qtd, "Quantidade", :class => 'control-label' %>
    <%= text_field_tag :qtd %>
  </p>
  <p>
    <%= label_tag :tipo, "Tipo de Operação", :class => 'control-label' %>
    <%= select_tag :tipo, options_for_select(["Adicionar", "Subtrair"]), :prompt => "Selecione" %>

    <%#= f.label :tipo, :class => 'control-label' %>

      <%#= f.select :tipo, ["Bebida", "Carne", "Mantimento", "Tempero"], :prompt => "Selecione", :class => 'text_field' %>
      <%#= f.text_field :tipo, :class => 'text_field' %>

    <%#= f.label :quantidade, :class => 'control-label' %>

      <%#= f.text_field :quantidade, :class => 'text_field' %>

    <%#= f.label :limite_minimo, :class => 'control-label' %>

      <%#= f.text_field :limite_minimo, :class => 'text_field' %>
  </p>
  <br>
  <p>
    <%= submit_tag "Confirmar", :class => 'button blue-cadastrar-top' %>
    <%#= link_to t('.atualizar_estoque', :default => t("helpers.links.atualizar_estoque")),
                      atualizar_estoque_produto_path, method: :post, :class => 'btn btn-mini' %>
    <%= link_to 'Cancelar', produtos_path, :class => 'button gray-voltar' %>
  </p>
</td>
  </table>
<% end %>

app/views/produtos/edit.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Editar %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/produtos/index.html.erb
<%- model_class = Produto -%>
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
  <br>

<div class="form-group">
<%= form_tag(produtos_path, :method => "get", :class => "form-horizontal", id: "search-form") do %>
    <div class="col-sm-2">
      <label>
        <%= text_field_tag :search, params[:search], :class => "form-control", placeholder: "Nome do Produto" %>
      </label>
    </div>
    <div class="col-sm-2">
      <label>    
       <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-success' %>
      </label>
    </div>       
    <% end %>
</div>
<br>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th>Qtd</th>
      <th>Limite Min</th>
      <th width="214px"><center><%=t '.ações', :default => t("helpers.ações") %><center></th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %> (<%= produto.produto_tipo.nome %>)</td>
        <td><%= produto.quantidade %> <%= unidade_medida(produto)%></td>
        <td><%= produto.limite_minimo %> <%= unidade_medida(produto) %></td>
        <td class="text-center">
          <%= link_to edit_produto_path(produto), html_options = { :class => 'btn btn-warning btn-sm', :title => "Editar Dados"} do %>
                      <span class="glyphicon glyphicon-pencil"></span>
                      <% end %>
          <%= link_to produto_path(produto), html_options = { :class => 'btn btn-info btn-sm', :title => "Ver Dados Completos"} do %>
                      <span class="glyphicon glyphicon-list-alt"></span>          
          <% end %>
          <%= link_to new_transacao_path(:produto_id => produto.id), :class => 'btn btn-primary btn-sm', :title => 'Adicionar/Subtrair' do %>          
                      <span class="glyphicon glyphicon-transfer"></span>
                      <% end %>
          <%#= link_to atualizar_produto_path(produto), method: :post, :class => 'button blue', :title => 'Adicionar/Subtrair' do %>          
                      <!-- <span class="operacoes"></span> -->
                      <%# end %>
          <%#= link_to produto_path(produto), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Deseja excluir esta produto?')) },
                      :class => 'button red', :title => "Remover" do %>
                      <!-- <span class="remover"></span> -->
                      <%# end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= will_paginate @produtos, renderer: BootstrapPagination::Rails %>

<div class="row">
        <div class="col-md-6 text-right "> 
        <%= link_to "Novo Produto", new_produto_path, :class => 'btn btn-primary' %>                  
        </div>        
         <div class="col-md-6">
          <%= link_to "Cancelar", home_inicial_path, :class => 'btn btn-default' %>
        </div>
</div>

app/views/produtos/new.html.erb
<%- model_class = Produto -%>
<div class="page-header">
 <h1>Novo Produto</h1>
</div>
<%= render :partial => 'form' %>

app/views/produtos/show.html.erb
<%- model_class = Produto -%>
<h2 class='titulo'><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
<br>
<div class="row">
    <div class="col-md-6">
      <ul class="list-group">
        <li class="list-group-item list-group-item-success"><strong>Dados Cadastrais</strong> 
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:nome) %>:&nbsp;</strong> 
          <%= @produto.nome %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:tipo) %>:&nbsp;</strong>
          <%= @produto.produto_tipo.nome %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:categoria) %>:&nbsp;</strong>
          <%= @produto.produto_categoria.nome %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:quantidade) %>:&nbsp;</strong>
          <%= @produto.quantidade %>
        </li>
        <li class="list-group-item"><strong>
          <%= model_class.human_attribute_name(:limite_minimo) %>:&nbsp;</strong>
          <%= @produto.limite_minimo %>
        </li>
      </ul>
    </div>
</div>
<br>

<div class="row">
  <div class="col-md-6 text-center">
        <div class="btn-group">
          <%= link_to produtos_path, :class => 'btn btn-default', :title => "Voltar" do %>
          <span class="glyphicon glyphicon-arrow-left"></span>
          <% end %>
        </div>
        <div class="btn-group">          
          <%= link_to new_transacao_path(:produto_id => @produto.id), :class => 'btn btn-primary', :title => 'Adicionar/Subtrair' do %> 
          <span class="glyphicon glyphicon-transfer"></span>
          <% end %>
        </div>
        <div class="btn-group">          
          <%= link_to new_produto_path, :class => 'btn btn-success', :title => "Novo Produto" do %>
          <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </div>        
        <div class="btn-group">          
          <%= link_to edit_produto_path, :class => 'btn btn-warning', :title => "Editar" do %>
          <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </div>
        <!-- <div class="btn-group"> -->
          <!-- <%#= link_to produto_path(@produto), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Deseja excluir esta produto?')) }, :class => 'btn btn-danger', :title => "Remover Produto" do %>     <span class="glyphicon glyphicon-remove"></span> -->
          <%# end %>
        <!-- </div>  -->
    </div>       
</div>

<h2> Dados de Movimentações</h2> <br><br> 
<table class="table table-striped">
          <thead>
            <tr>
              <th>Tipo</th>
              <th>Quantidade</th>
              <th>Data de Lançamento</th>
            </tr>
          </thead>
          <tbody>
            <% @produto.transacoes.each do |transacao| %>
              <tr>
              <td> <%= transacao.tipo == 1 ? "Entrada" : "Saída" %> </td>
                <td><%= transacao.quantidade %></td>
                <td><%= transacao.created_at.strftime("%d/%m/%Y") %></td>
              </tr>
            <% end %>
          </tbody>
        </table><br>  